spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/hao?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai"